export const demoNotebook = {
  id: 'demo-computer-architecture',
  title: 'Computer Architecture and Memory Systems',
  description: 'A public notebook demonstrating source evidence, a multi-topic concept graph, six teach-back cases, tutoring, review, attempt comparison, and workflow tracing.',
  source: {
    title: 'Computer architecture — guided source',
    body: 'A processor executes instructions through a datapath controlled by a control unit. The instruction cycle includes fetch, decode, execute, memory access, and write-back. Registers hold immediate operands and results. An arithmetic logic unit performs arithmetic and logical operations. Pipelining overlaps instruction stages to improve throughput, but hazards can interrupt the flow. Data hazards arise from dependencies, control hazards arise from branches, and structural hazards arise when hardware resources are insufficient. Branch prediction reduces control-hazard cost by guessing the next instruction path. Computer systems also organise storage as a hierarchy. Registers are the smallest and fastest storage locations. Cache stores recently or frequently used blocks close to the processor and is organised in lines and levels. Main memory holds active programs and data but is volatile. Virtual memory maps program addresses to physical memory and moves pages between main memory and secondary storage when needed. A page fault occurs when a required page is absent from physical memory. Temporal and spatial locality explain why caches work. A cache hit serves data from cache; a miss fetches it from a lower level and incurs a miss penalty. Address buses identify locations, data buses carry values, and control buses carry coordination signals. Interrupts suspend the normal instruction sequence so the processor can service an event. Direct memory access lets a controller transfer data between an I/O device and memory with limited processor involvement. Instruction-set architecture defines the programmer-visible instructions, registers, data types, and addressing modes, while microarchitecture defines how a processor implements that architecture.',
  },
  concepts: [
    { id: 'isa', label: 'Instruction-set architecture', level: 'Interface', evidence: 'defines programmer-visible instructions, registers, data types, and addressing modes' },
    { id: 'microarchitecture', label: 'Microarchitecture', level: 'Implementation', evidence: 'defines how a processor implements an instruction-set architecture' },
    { id: 'instruction-cycle', label: 'Instruction cycle', level: 'Process', evidence: 'fetch, decode, execute, memory access, and write-back' },
    { id: 'control-unit', label: 'Control unit', level: 'CPU', evidence: 'coordinates the datapath and instruction execution' },
    { id: 'datapath', label: 'Datapath', level: 'CPU', evidence: 'moves and transforms operands during instruction execution' },
    { id: 'alu', label: 'Arithmetic logic unit', level: 'CPU', evidence: 'performs arithmetic and logical operations' },
    { id: 'registers', label: 'Registers', level: 'Memory L0', evidence: 'hold immediate operands and results and are the fastest storage locations' },
    { id: 'pipeline', label: 'Instruction pipeline', level: 'CPU', evidence: 'overlaps instruction stages to improve throughput' },
    { id: 'data-hazard', label: 'Data hazard', level: 'Hazard', evidence: 'arises from dependencies between instructions' },
    { id: 'control-hazard', label: 'Control hazard', level: 'Hazard', evidence: 'arises from branches and uncertain control flow' },
    { id: 'structural-hazard', label: 'Structural hazard', level: 'Hazard', evidence: 'arises when hardware resources are insufficient' },
    { id: 'branch-prediction', label: 'Branch prediction', level: 'Technique', evidence: 'reduces control-hazard cost by guessing the next instruction path' },
    { id: 'cache', label: 'Cache', level: 'Memory L1', evidence: 'stores recently or frequently used blocks close to the processor' },
    { id: 'cache-levels', label: 'Cache levels', level: 'Structure', evidence: 'cache is organised in multiple levels' },
    { id: 'cache-line', label: 'Cache line', level: 'Unit', evidence: 'cache is organised in blocks or lines' },
    { id: 'memory', label: 'Main memory', level: 'Memory L2', evidence: 'holds active programs and data but is volatile' },
    { id: 'virtual-memory', label: 'Virtual memory', level: 'Abstraction', evidence: 'maps program addresses to physical memory' },
    { id: 'page-fault', label: 'Page fault', level: 'Event', evidence: 'required page is absent from physical memory' },
    { id: 'storage', label: 'Secondary storage', level: 'Memory L3', evidence: 'non-volatile storage used for persistent data and paging' },
    { id: 'temporal', label: 'Temporal locality', level: 'Principle', evidence: 'recently accessed data is likely to be accessed again' },
    { id: 'spatial', label: 'Spatial locality', level: 'Principle', evidence: 'nearby data is likely to be accessed soon' },
    { id: 'hit', label: 'Cache hit', level: 'Outcome', evidence: 'requested data is found in cache' },
    { id: 'miss', label: 'Cache miss', level: 'Outcome', evidence: 'data is fetched from a lower level' },
    { id: 'miss-penalty', label: 'Miss penalty', level: 'Measure', evidence: 'additional time required after a cache miss' },
    { id: 'address-bus', label: 'Address bus', level: 'Interconnect', evidence: 'identifies memory or I/O locations' },
    { id: 'data-bus', label: 'Data bus', level: 'Interconnect', evidence: 'carries values between components' },
    { id: 'control-bus', label: 'Control bus', level: 'Interconnect', evidence: 'carries coordination and control signals' },
    { id: 'interrupt', label: 'Interrupt', level: 'Control', evidence: 'suspends normal execution so an event can be serviced' },
    { id: 'dma', label: 'Direct memory access', level: 'I/O', evidence: 'moves data between I/O and memory with limited processor involvement' },
  ],
  edges: [
    ['isa', 'microarchitecture', 'implemented by'], ['microarchitecture', 'datapath', 'contains'], ['microarchitecture', 'control-unit', 'contains'],
    ['instruction-cycle', 'datapath', 'uses'], ['instruction-cycle', 'control-unit', 'coordinated by'], ['datapath', 'alu', 'contains'], ['datapath', 'registers', 'contains'],
    ['pipeline', 'instruction-cycle', 'overlaps'], ['data-hazard', 'pipeline', 'stalls'], ['control-hazard', 'pipeline', 'stalls'], ['structural-hazard', 'pipeline', 'stalls'], ['branch-prediction', 'control-hazard', 'reduces'],
    ['registers', 'cache', 'faster than'], ['cache', 'memory', 'faster than'], ['memory', 'storage', 'faster than'], ['cache-levels', 'cache', 'part of'], ['cache-line', 'cache', 'unit of'],
    ['temporal', 'cache', 'explains'], ['spatial', 'cache-line', 'explains'], ['hit', 'cache', 'depends on'], ['miss', 'cache', 'depends on'], ['miss', 'miss-penalty', 'causes'],
    ['virtual-memory', 'memory', 'maps to'], ['page-fault', 'virtual-memory', 'depends on'], ['page-fault', 'storage', 'may fetch from'],
    ['address-bus', 'memory', 'selects'], ['data-bus', 'memory', 'transfers data'], ['control-bus', 'control-unit', 'coordinates'], ['interrupt', 'control-unit', 'signals'], ['dma', 'memory', 'transfers to'], ['dma', 'data-bus', 'uses'],
  ],
  scenarios: [
    { id: 'grounded', label: 'Grounded explanation', response: 'The ISA defines what software can use, while microarchitecture implements it. Instructions move through fetch, decode, execute, memory access, and write-back. Pipelining overlaps those stages, but hazards can stall the flow. Registers and cache reduce access time, and locality explains why cache hits are common.', state: 'Understood', confidence: 'Strong evidence', gaps: [], nextAction: 'Schedule a light review', review: 'Review after a longer interval; no tutoring required.' },
    { id: 'partial', label: 'Partial but grounded', response: 'A pipeline runs several instructions at once, and cache is faster than main memory.', state: 'Partial', confidence: 'Grounded but incomplete', gaps: ['Pipeline stages are not explained', 'Hazards are omitted', 'Locality and cache misses are omitted'], nextAction: 'Teach back again', review: 'Short interval after another explanation.' },
    { id: 'shallow', label: 'Shallow definition', response: 'The CPU executes instructions and memory stores data.', state: 'Emerging', confidence: 'Incomplete evidence', gaps: ['No instruction-cycle mechanism', 'No distinction between ISA and microarchitecture', 'No memory hierarchy explanation'], nextAction: 'Ask for elaboration', review: 'Immediate second attempt.' },
    { id: 'prerequisite', label: 'Missing prerequisite', response: 'A page fault means the cache missed an instruction in the pipeline.', state: 'Needs review', confidence: 'Prerequisite confusion', gaps: ['Page faults belong to virtual memory', 'Cache misses and page faults are different events', 'Pipeline stages are unrelated to page residency'], nextAction: 'Repair the prerequisite', review: 'Tutor on virtual memory before another attempt.' },
    { id: 'unsupported', label: 'Unsupported confidence', response: 'Every processor has five pipeline stages, exactly three cache levels, and all misses go directly to SSD.', state: 'Needs review', confidence: 'Unsupported claims', gaps: ['Pipeline depth is not fixed by the source', 'Cache-level count is not guaranteed', 'A miss may be served by another cache level or main memory'], nextAction: 'Request evidence', review: 'Correct unsupported claims before review.' },
    { id: 'misconception', label: 'Direct misconception', response: 'The ISA is the physical circuit, branch prediction removes every control hazard, and main memory is permanent storage.', state: 'Misconception', confidence: 'Contradicted by source', gaps: ['ISA is the programmer-visible interface, not the physical circuit', 'Branch prediction reduces cost but does not remove every control hazard', 'Main memory is volatile'], nextAction: 'Open Socratic tutoring', review: 'Immediate corrective review after tutoring.' },
  ],
  tutor: [
    { role: 'system', text: 'Focus: ISA versus implementation, branch prediction, and volatility.' },
    { role: 'tutor', text: 'Does the ISA describe the programmer-visible contract or the physical circuit that implements it?' },
    { role: 'learner', text: 'It describes the programmer-visible contract. Microarchitecture implements it.' },
    { role: 'tutor', text: 'Does branch prediction guarantee the correct path, or reduce the cost when its guess is useful?' },
    { role: 'learner', text: 'It only predicts. A wrong prediction still creates a penalty.' },
    { role: 'tutor', text: 'Which storage level loses data when power is removed: main memory or secondary storage?' },
    { role: 'learner', text: 'Main memory is volatile; secondary storage is persistent.' },
    { role: 'tutor', text: 'Rebuild the explanation using ISA, microarchitecture, branch prediction, and volatility.' },
  ],
  trace: [
    ['route_query', 'misconception diagnosis workflow', 'completed'],
    ['retrieve_evidence', '12 source-linked candidates', 'completed'],
    ['fuse_candidates', 'dense and sparse result set', 'completed'],
    ['traverse_concept_graph', '3 bounded relationship paths', 'completed'],
    ['validate_grounding', '3 contradicted claims found', 'completed'],
    ['classify_gaps', 'misconception and missing relationship', 'completed'],
    ['calculate_mastery', 'misconception override applied', 'completed'],
    ['select_next_action', 'Socratic tutoring', 'completed'],
    ['persist_demo_result', 'No account data written', 'completed'],
  ],
} as const;
