export const demoNotebook = {
  id: 'demo-memory-hierarchy',
  title: 'Computer Memory Hierarchy',
  description: 'A public notebook demonstrating evidence, concept relationships, six teach-back cases, tutoring, review, attempt comparison, and workflow tracing.',
  source: {
    title: 'Memory hierarchy — compact study source',
    body: 'Computer systems organise storage as a hierarchy. CPU registers are the smallest and fastest storage locations. Cache sits between the processor and main memory and stores copies of recently or frequently used data. Cache is organised in lines and commonly has multiple levels. Main memory, usually DRAM, holds active programs and data but loses its contents when power is removed. Virtual memory maps program addresses to physical memory and may move pages between main memory and secondary storage. A page fault occurs when a required page is not currently in physical memory. Secondary storage such as solid-state drives is slower but non-volatile and provides much larger capacity. Locality explains why caches work: temporal locality means recently accessed data is likely to be accessed again, while spatial locality means nearby data is likely to be accessed soon. A cache hit occurs when requested data is found in cache. A cache miss fetches it from a lower, slower level. Hit rate and miss penalty together influence effective access time. Higher levels are faster, smaller, and more expensive per bit; lower levels are slower, larger, and cheaper per bit.',
  },
  concepts: [
    { id: 'registers', label: 'Registers', level: 'L0', evidence: 'smallest and fastest storage locations' },
    { id: 'cache', label: 'Cache', level: 'L1', evidence: 'stores copies of recently or frequently used data' },
    { id: 'cache-levels', label: 'Cache levels', level: 'Structure', evidence: 'cache commonly has multiple levels' },
    { id: 'cache-line', label: 'Cache line', level: 'Unit', evidence: 'cache is organised in lines' },
    { id: 'memory', label: 'Main memory', level: 'L2', evidence: 'holds active programs and data but loses contents without power' },
    { id: 'virtual-memory', label: 'Virtual memory', level: 'Abstraction', evidence: 'maps program addresses to physical memory' },
    { id: 'page-fault', label: 'Page fault', level: 'Event', evidence: 'required page is not currently in physical memory' },
    { id: 'storage', label: 'Secondary storage', level: 'L3', evidence: 'slower but non-volatile and much larger' },
    { id: 'temporal', label: 'Temporal locality', level: 'Principle', evidence: 'recently accessed data is likely to be accessed again' },
    { id: 'spatial', label: 'Spatial locality', level: 'Principle', evidence: 'nearby data is likely to be accessed soon' },
    { id: 'hit', label: 'Cache hit', level: 'Outcome', evidence: 'requested data is found in cache' },
    { id: 'miss', label: 'Cache miss', level: 'Outcome', evidence: 'fetches data from a lower, slower level' },
    { id: 'hit-rate', label: 'Hit rate', level: 'Measure', evidence: 'influences effective access time' },
    { id: 'miss-penalty', label: 'Miss penalty', level: 'Measure', evidence: 'influences effective access time' },
  ],
  edges: [
    ['registers', 'cache', 'faster than'], ['cache', 'memory', 'faster than'], ['memory', 'storage', 'faster than'],
    ['temporal', 'cache', 'explains'], ['spatial', 'cache-line', 'explains'], ['cache-levels', 'cache', 'part of'],
    ['hit', 'cache', 'depends on'], ['miss', 'cache', 'depends on'], ['miss', 'miss-penalty', 'causes'],
    ['hit-rate', 'cache', 'measures'], ['virtual-memory', 'memory', 'maps to'], ['page-fault', 'virtual-memory', 'depends on'],
    ['page-fault', 'storage', 'may fetch from'],
  ],
  scenarios: [
    { id: 'grounded', label: 'Grounded explanation', response: 'Registers are fastest and smallest. Cache keeps nearby copies and works because of temporal and spatial locality. Main memory is larger but volatile, while SSD storage is slower and non-volatile. A cache miss fetches data from a lower level and adds a miss penalty.', state: 'Understood', confidence: 'Strong evidence', gaps: [], nextAction: 'Schedule a light review', review: 'Review after a longer interval; no tutoring required.' },
    { id: 'partial', label: 'Partial but grounded', response: 'Cache is faster than main memory and keeps recently used information close to the processor. Main memory holds active programs.', state: 'Partial', confidence: 'Grounded but incomplete', gaps: ['Does not explain spatial locality', 'Does not distinguish hits from misses', 'Does not discuss volatility'], nextAction: 'Teach back again', review: 'Short interval after another explanation.' },
    { id: 'shallow', label: 'Shallow definition', response: 'Cache makes computers faster because it stores memory.', state: 'Emerging', confidence: 'Incomplete evidence', gaps: ['Mechanism is not explained', 'Locality is omitted', 'Hierarchy levels are not compared'], nextAction: 'Ask for elaboration', review: 'Immediate second attempt.' },
    { id: 'prerequisite', label: 'Missing prerequisite', response: 'A page fault means the cache missed the requested byte.', state: 'Needs review', confidence: 'Prerequisite confusion', gaps: ['Page faults belong to virtual memory', 'Cache misses and page faults are different events', 'Physical-memory mapping is missing'], nextAction: 'Repair the prerequisite', review: 'Tutor on virtual memory before another attempt.' },
    { id: 'unsupported', label: 'Unsupported confidence', response: 'L1 cache always has exactly 64 kilobytes and every miss goes directly to SSD.', state: 'Needs review', confidence: 'Unsupported claims', gaps: ['Capacity is not supported by the source', 'A miss may be served by another cache level or main memory', 'The claim ignores the hierarchy'], nextAction: 'Request evidence', review: 'Correct unsupported claims before review.' },
    { id: 'misconception', label: 'Direct misconception', response: 'Main memory is permanent storage and cache is slower because it is smaller.', state: 'Misconception', confidence: 'Contradicted by source', gaps: ['Main memory is volatile, not permanent', 'Cache is faster, not slower', 'Size does not make cache slower'], nextAction: 'Open Socratic tutoring', review: 'Immediate corrective review after tutoring.' },
  ],
  tutor: [
    { role: 'system', text: 'Focus: volatility and relative speed.' },
    { role: 'tutor', text: 'Which level keeps its data after power is removed: main memory or secondary storage?' },
    { role: 'learner', text: 'Secondary storage keeps its data. Main memory is volatile.' },
    { role: 'tutor', text: 'Now compare cache and main memory: which is closer to the processor, and why does that matter?' },
    { role: 'learner', text: 'Cache is closer and faster, so a hit avoids waiting for main memory.' },
    { role: 'tutor', text: 'Rebuild the original explanation using volatility, relative speed, and cache hits.' },
  ],
  trace: [
    ['route_query', 'misconception diagnosis workflow', 'completed'],
    ['retrieve_evidence', '8 source-linked candidates', 'completed'],
    ['fuse_candidates', 'dense + sparse result set', 'completed'],
    ['traverse_concept_graph', '2-hop bounded context', 'completed'],
    ['validate_grounding', '2 contradicted claims found', 'completed'],
    ['classify_gaps', 'misconception + missing relation', 'completed'],
    ['calculate_mastery', 'misconception override applied', 'completed'],
    ['select_next_action', 'Socratic tutoring', 'completed'],
    ['persist_demo_result', 'No account data written', 'completed'],
  ],
} as const;
