import { TutoringDecision, TutoringMove, TutoringSession, TutoringTurn } from './types';
import { getDeterministicMove } from './socratic-policy';

export interface DecisionContext {
  session: TutoringSession;
  previousTurns: TutoringTurn[];
  availableSourceChunkIds: string[];
}

/**
 * Core deterministic engine for tutoring.
 * Selects the next move, checks caps, and returns a structural decision.
 */
export function decideNextMove(context: DecisionContext): TutoringDecision {
  const { session, previousTurns, availableSourceChunkIds } = context;

  // Filter out system/student turns to count actual tutor pedagogical moves
  const tutorMoves = previousTurns
    .filter(t => t.role === 'tutor' && t.tutorMove)
    .map(t => t.tutorMove!);

  // If max turns reached, summarize and recommend review
  if (session.currentTurnCount >= session.maxTurns) {
    return {
      nextMove: 'summarize_progress',
      question: 'We have reached the end of this guided session. Please review your understanding and attempt a teach-back again.',
      sourceChunkIds: [],
      gapFindingIds: [],
      shouldUpdateMastery: false,
      shouldCompleteSession: true,
      reason: 'Max turns reached. Summarizing and stopping to prevent infinite loops.',
      confidenceScore: 1.0,
    };
  }

  // Get the next move based on policy
  const nextMove = getDeterministicMove(session.focusType, tutorMoves);

  // Determine if we should complete on this move
  const shouldCompleteSession = nextMove === 'request_teach_back_again' || nextMove === 'complete_session' || nextMove === 'summarize_progress';

  return {
    nextMove,
    // The actual question text will be generated by the AI phrasing engine later.
    // We provide a deterministic fallback placeholder here.
    question: getFallbackQuestion(nextMove),
    sourceChunkIds: availableSourceChunkIds,
    gapFindingIds: [], // Typically we'd map this if we tracked specific gaps
    shouldUpdateMastery: false, // Tutoring MUST NOT directly update mastery
    shouldCompleteSession,
    reason: `Deterministic policy escalated to ${nextMove} based on ${tutorMoves.length} previous tutor moves for ${session.focusType}.`,
    confidenceScore: 1.0,
  };
}

function getFallbackQuestion(move: TutoringMove): string {
  switch (move) {
    case 'ask_contrast_question':
      return 'How does this compare to the correct concept mentioned in the source?';
    case 'ask_evidence_question':
      return 'Can you point to the specific part of the source material that supports this?';
    case 'provide_small_hint':
      return 'Think about how the source describes the key differences.';
    case 'ask_correction':
      return 'Actually, the source states something different. Can you correct your explanation based on the source?';
    case 'request_teach_back_again':
      return 'Let us try teaching this concept again from the beginning to see if it is clearer now.';
    case 'ask_prerequisite_question':
      return 'Before we go further, can you explain the underlying foundation for this?';
    case 'ask_clarifying_question':
      return 'Could you elaborate a bit more on what you mean?';
    case 'ask_example_question':
      return 'Can you give an example of how that works?';
    case 'summarize_progress':
      return 'Let us summarize what we discussed. Please try the teach-back again when you are ready.';
    case 'complete_session':
      return 'Great job working through that! Please try a fresh teach-back to demonstrate your new understanding.';
    default:
      return 'Can you tell me more about that?';
  }
}
